name: PR Summary Generator

on:
    workflow_dispatch:
  
    pull_request:
      branches:
        - main
  
    push:
      branches:
        - main
concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr_summary:
    runs-on: ubuntu-latest
    name: PR Summarizer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Summarize PR with AI
        uses: behrouz-rad/ai-pr-summarizer@v1
        with:
          llm-model: 'deepseek-coder-v2:latest'
          prompt-file: ./assets/prompt1.txt
          models-file: ./assets/ai-models.txt
          version-file: ./assets/ollama-version.txt
          context-window: 4096
          upload-changes: true
          fail-on-error: true